all:
	latex jdavid-jdecker-nb-text-classifier.tex
	bibtex jdavid-jdecker-nb-text-classifier
	latex jdavid-jdecker-nb-text-classifier.tex
	pdflatex jdavid-jdecker-nb-text-classifier.tex

clean:
	rm -rf jdavid-jdecker-nb-text-classifier.pdf
	rm -rf *.aux *.bbl *.blg *blx.bib *.dvi *.log *.out
	rm -rf *.run.xml
